export const GET_DASHBOARD_STATUS = "GET_DASHBOARD_STATUS";
export const GET_DASHBOARD_STATUS_SUCCESS = "GET_DASHBOARD_STATUS_SUCCESS";
export const GET_DASHBOARD_STATUS_ERROR = "GET_DASHBOARD_STATUS_ERROR";

export const GET_REPETITIVE_TASKS = "GET_REPETITIVE_TASKS";
export const GET_REPETITIVE_TASKS_SUCCESS = "GET_REPETITIVE_TASKS_SUCCESS";
export const GET_REPETITIVE_TASKS_ERROR = "GET_REPETITIVE_TASKS_ERROR";

export const GET_DAILY_TASKS = "GET_DAILY_TASKS";
export const GET_DAILY_TASKS_SUCCESS = "GET_DAILY_TASKS_SUCCESS";
export const GET_DAILY_TASKS_ERROR = "GET_DAILY_TASKS_ERROR";
export const GET_WEEK_TASKS = "GET_WEEK_TASKS";
export const GET_WEEK_TASKS_SUCCESS = "GET_WEEK_TASKS_SUCCESS";
export const GET_WEEK_TASKS_ERROR = "GET_WEEK_TASKS_ERROR";
export const GET_PLAN_TASKS = "GET_PLAN_TASKS";
export const GET_PLAN_TASKS_SUCCESS = "GET_PLAN_TASKS_SUCCESS";
export const GET_PLAN_TASKS_ERROR = "GET_PLAN_TASKS_ERROR";
